In [1]:
import gensim
import json

In [2]:
model= gensim.models.KeyedVectors.load_word2vec_format('/home/azureuser/GoogleNews-vectors-negative300.bin.gz',binary=True)

In [3]:
indent='India'
similar_words=model.most_similar(indent,topn=50)
print(similar_words)

[('Indias', 0.7384199500083923), ('Indiaâ_€_™', 0.6843485832214355), ('Pakistan', 0.6706861257553101), ('Delhi', 0.6632035970687866), ('Bangalore', 0.6583030819892883), ('subcontinent', 0.6579217910766602), ('Bangladesh', 0.6527796983718872), ('sub_continent', 0.6503037214279175), ('Mumbai', 0.6495687961578369), ('Sri_Lanka', 0.6445952653884888), ('Chennai', 0.6421363353729248), ('Hyderabad', 0.6390925645828247), ('Gujarat', 0.638266921043396), ('Maurice_Quadras_Mangalore', 0.6347160339355469), ('Maharashtra', 0.6283520460128784), ('Indian', 0.6271833181381226), ('Mukherjee', 0.6240410804748535), ('Alwine_Goveas_Kulshekar_Mangalore', 0.6223571300506592), ('Nepal', 0.6177759170532227), ('Kolkata', 0.6175625324249268), ('lndia', 0.6101034879684448), ('West_Bengal', 0.6090282797813416), ('Tamil_Nadu', 0.6058955788612366), ('Bangaldesh', 0.6016401052474976), ('Inida', 0.6014565229415894), ('China', 0.600421130657196), ('Karnataka', 0.5983072519302368), ('Bharat', 0.5947712659835815), ('Andhra_Pradesh', 0.5941009521484375), ('Rajasthan', 0.5929971933364868), ('Jaipur', 0.5909463167190552), ('Uttar_Pradesh', 0.586546778678894), ('India.The', 0.5857070088386536), ('NEW_DELHI', 0.5848248600959778), ('Lanka', 0.5810680985450745), ('DDNEWS', 0.5808542370796204), ('Manmohan', 0.5787777900695801), ('worldover', 0.578484296798706), ('Kerala', 0.5782361030578613), ('Madhya_Pradesh', 0.5782033801078796), ('Bihar', 0.5765769481658936), ('INDIA', 0.5751368999481201), ('ndia', 0.5737785696983337), ('Maharastra', 0.5728194713592529), ('Himachal', 0.5724326372146606), ('Pune', 0.571716845035553), ('Sachin', 0.570521891117096), ('Hindustan_Times', 0.5672290921211243), ('Ahmedabad', 0.5668432712554932), ('Prime_Minister_Manmohan_Singh', 0.5663041472434998)]

In [ ]:
similar= [str(similar_words[i][0]) for i in range (len(similar_words))]

In [ ]:
similar

In [79]:
indent =['greetings','yes','help','lease','buy','lottery','finance','options','entertainment','performance','personal','travel',
'weekend','outing','kit','anything',
'thanks','bye','about','wassup','anything','no','reveal',
'hobby','opportunity','hassle','change','frequently']
import pandas as pd
SYN =pd.DataFrame()
A =pd.DataFrame()
for i in range(len(indent)): 
    SYN['indents']=indent[i]
    similar_words=model.most_similar(indent[i],topn=50)
    similar= [str(similar_words[i][0]) for i in range (len(similar_words))]
    SYN['Synonyms']=similar
    A=A.append(SYN)

In [73]:
'finance','options','entertainment''performance','personal','travel,'
'weekend','outing','kit','anything'
'thanks','bye','about','wassup','anything','no','reveal'
'hobby','opportunity','hassle','change','frequently'

   indents                      Synonyms
0      NaN                    courageous
1      NaN                       bravely
2      NaN                       bravest
3      NaN                       valiant
4      NaN                       gallant
5      NaN                  courageously
6      NaN                       courage
7      NaN                   brave_souls
8      NaN                      fearless
9      NaN                        heroic
10     NaN                       bravery
11     NaN                 stout_hearted
12     NaN                         gutsy
13     NaN                        daring
14     NaN                    heroically
15     NaN                     couragous
16     NaN                  lion_hearted
17     NaN                     braveness
18     NaN                       doughty
19     NaN                     dauntless
20     NaN                     wave_O'er
21     NaN                      resolute
22     NaN  artistic_kleptomaniac_clumsy
23     NaN                      selfless
24     NaN                      intrepid
25     NaN                     foolhardy
26     NaN                     valiantly
27     NaN                        ballsy
28     NaN                fought_bravely
29     NaN                     gallantly
..     ...                           ...
20     old    La'Shaun_Armstrong_escaped
21     old                daughter_Zuhur
22     old                        nephew
23     old                       Ninteen
24     old          Alephonsion_Deng_saw
25     old               Lainaina_Pierre
26     old          Mayor_Onesimo_Cuevas
27     old                      monthold
28     old              Antonio_Lamonica
29     old                    ##year_old
30     old               Shawnita_McNeil
31     old                      grandson
32     old                  Leah_Questin
33     old                  stepdaughter
34     old                      Lil_dadA
35     old                DEAR_ABBY_I'ma
36     old                   Joshua_Sipe
37     old                         QI'ma
38     old                Pit_bull_mauls
39     old             Eleonora_Calesini
40     old              Giacomo_Gallazzi
41     old            Shoaib_alias_Soheb
42     old                    Iman_Kazim
43     old                       teenage
44     old              Brandy_Fenderson
45     old                daughter_Hanah
46     old                 Landen_Pierre
47     old                Chase_Dreyfous
48     old                    precocious
49     old           son_Filippo_Norelli

[100 rows x 2 columns]

In [85]:
A.to_csv('synonyms.csv')